#!/usr/bin/env bash
# Function to print domain and subdomain information
print_domain_subdomain () {
    local subdomain=$2
    local domain=$1
    local record=$(dig +short $subdomain.$domain | awk '{print $1}')
    local destination=$(dig +short $subdomain.$domain)

    if [ -z "$record" ]; then
        echo "The subdomain $subdomain does not exist for domain $domain."
    else
        echo "The subdomain $subdomain is a $record record and points to $destination"
    fi
}

# Main function to handle script logic
if [ "$#" -eq 2 ]; then
    print_domain_subdomain "$1" "$2"
else
    print_domain_subdomain "$1" "www"
    print_domain_subdomain "$1" "lb-01"
    print_domain_subdomain "$1" "web-01"
    print_domain_subdomain "$1" "web-02"
fi
