#!/usr/bin/env bash
# Check if an argument is provided
# Extract IP address from the argument
# Ping the IP address 5 times and display round-trip time.

if [ $# -eq 0 ]
then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
  ping -c 5 "$1"
fi
