#!/usr/bin/env bash
# Function to handle SIGTERM and SIGQUIT signals
# Function to handle SIGINT signal
# Trap SIGTERM, SIGQUIT, and SIGINT signals and call the corresponding function

terminator() {
  rm /var/run/myscript.pid
  exit
}

echo "$$" > /var/run/myscript.pid

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && terminator' SIGTERM
  trap 'terminator' SIGQUIT
done
