#!/usr/bin/env bash
# Using a while loop to iterate from 1 to 10.
counter=0
while [ $counter -lt 10 ]
do
    # Use if, elif, else statements to display messages based on loop iteration
    if [ $counter -eq 3 ]; then
        echo "bad luck"
    elif [ $counter -eq 7 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi

    ((counter++))
done
