#!/usr/bin/env bash
# Initialize a counter.

counter=1

# Using a while loop to iterate from 1 to 20.

while [ $counter -le 20 ]
do
  echo "$counter"
  case $counter in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( counter++ ))
done
