#!/usr/bin/env bash
# Initialize variables
hour=0

# Using a while loop to display time for 12 hours and 59 minutes.

while [ $hour -le 12 ]
do
  echo "Hour: $hour"
  minute=1
  while [ $minute -le 59 ]
  do
    echo "$minute"
    (( minute++ ))
  done
  (( hour++ ))
done
