#!/usr/bin/env bash
# Using a for loop to iterate over files in the current directory
for file in *
do
    # Check if the file is not a hidden file
    if [[ $file != .* ]]; then
        # Extract the part of the name after the first dash
        name_part=$(echo "$file" | cut -d'-' -f2-)

        # Display the formatted output
        echo "$name_part"
    fi
done
