#!/usr/bin/env bash
# Get a list of all network interfaces
# Iterate through each interface and display its IPv4 addresses
# Check if the interface has an IPv4 address

ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | cut -b 11-
