#!/usr/bin/env bash

openssl genrsa -aes256 -passout pass:betty -out ~/.ssh/school.pem 4096
openssl rsa -passin pass:betty -in ~/.ssh/school.pem -pubout -out ~/.ssh/school.pub
chmod 600 ~/.ssh/school.pem
