#!/usr/bin/env bash

echo "Generating public/private rsa key pair."
openssl genrsa -aes256 -passout pass:betty -out ~/.ssh/school.pem 4096
openssl rsa -passin pass:betty -in ~/.ssh/school.pem -pubout -out ~/.ssh/school.pub
chmod 600 ~/.ssh/school.pem
echo "Your identification has been saved in school."
echo "Your public key has been saved in school.pub."
echo "The key fingerprint is:"
ssh-keygen -lf ~/.ssh/school.pub
echo "The key's randomart image is:"
ssh-keygen -lvf ~/.ssh/school.pub
